<?xml version="1.0"?>
<package format="2">
  <name>costmap_cspace_rviz_plugins</name>
  <version>0.1.0</version>
  <description>Rviz plugins for costmap_cspace_msgs</description>
  <maintainer email="tomohiro.oku2023@gmail.com">Tomohiro Oku</maintainer>
  <license>BSD</license>
  <author email="nhatao@seqsense.com">Naotaka Hatao</author>
  <author email="tomohiro.oku2023@gmail.com">Tomohiro Oku</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>costmap_cspace_msgs</depend>
  <depend>rviz2</depend>

  <depend>libqt5-core</depend>
  <depend>libqt5-gui</depend>
  <depend>libqt5-widgets</depend>
  <depend>qtbase5-dev</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
